[project]
name = 'Multiverse-Asset-Exchange-'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.cross-universal-value-conversion]
path = 'contracts/cross-universal-value-conversion.clar'
clarity_version = 2
epoch = 2.5

[contracts.inter-reality-asset-tokenization]
path = 'contracts/inter-reality-asset-tokenization.clar'
clarity_version = 2
epoch = 2.5

[contracts.multiverse-liquidity-pool]
path = 'contracts/multiverse-liquidity-pool.clar'
clarity_version = 2
epoch = 2.5

[contracts.reality-divergence-risk-assessment]
path = 'contracts/reality-divergence-risk-assessment.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
